### ISSUE TITLE
Refactor each embed to import standalone React components

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/boba-editor#58]
See this commit for a proof of concept: https://github.com/BobaBoard/boba-editor/commit/6222706243c412f0150f449302bd0bf5550eace6

## Goals
- Make embeds code more portable
- Decouple embeds code from Quill editor
- Make SSR easier
- Simplify render cycle of embeds

## Todo
- [ ] Write design doc
- [ ] Recreate base components in React (e.g. editor overlay, loading overlay, spoilers overlay)
- [ ] Rewrite components with the new system
